### ISSUE TITLE
Please put this on pypi

### ISSUE THREAD

**Issue by GoogleCodeExporter** [esainane/pyp#6]
```
That will make it easier to install.
```

Original issue reported on code.google.com by `msabr...@gmail.com` on 11 Mar 2012 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
I've been pushing to get pyp merged into homebrew for easy installation on Macs 
[1]

You're more than welcome to chime in and +1 the request.

[1] - https://github.com/mxcl/homebrew/pull/9737
```

Original comment by `yuv....@gmail.com` on 11 Mar 2012 at 1:33

**Comment by GoogleCodeExporter** [comment]
```
It's in Homebrew now! Next stop: PyPI! :-)
```

Original comment by `msabr...@gmail.com` on 11 Mar 2012 at 4:56

**Comment by GoogleCodeExporter** [comment]
```
Indeed it is has been merged upstream several hours ago!

PyPI is less under my control ;)

I'll cntinue updating the brew formula on any new release.
```

Original comment by `yuv....@gmail.com` on 11 Mar 2012 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
I added the latest version here:

http://pypi.python.org/pypi/pyp/2.11

thanks all,

t
```

Original comment by `tobyro...@gmail.com` on 12 Mar 2012 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Now it's on Pypi I was expecting pip to work:

  $ sudo pip install pyp

  Downloading/unpacking pyp

    Could not find any downloads that satisfy the requirement pyp

  No distributions at all found for pyp

  Storing complete log in /Users/me/.pip/pip.log

```

Original comment by `andybak` on 16 Mar 2012 at 4:05

**Comment by GoogleCodeExporter** [comment]
```
Ditto. pip install doesn't work for me either.

I think that this is because the release has no files associated with it. If 
you look at pypi for most packages, they have a "files" section with a tar.gz 
file.

http://pypi.python.org/pypi/pyp/2.11 does not.

So I think you need to upload a file.
```

Original comment by `msabr...@gmail.com` on 16 Mar 2012 at 9:28

**Comment by GoogleCodeExporter** [comment]
```
ok, thanks for the info. I'll get a tar ball up there when I get a chance.

t

```

Original comment by `tobyro...@gmail.com` on 16 Mar 2012 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
it is removed from Homebrew and it still don't work on pypi
```

Original comment by `ibrka...@gmail.com` on 18 Mar 2012 at 11:04

**Comment by GoogleCodeExporter** [comment]
```
Why was it removed from Homebrew?
```

Original comment by `msabr...@gmail.com` on 18 Mar 2012 at 11:18

**Comment by GoogleCodeExporter** [comment]
```
reason was that it is now on pypi.
```

Original comment by `ibrka...@gmail.com` on 18 Mar 2012 at 11:36

**Comment by GoogleCodeExporter** [comment]
```
I guess if one is desperate to install pyp they can do something like:

wget -O $(which python)/pyp http://pyp.googlecode.com/files/pyp && chmod +x 
$(which python)/pyp

```

Original comment by `msabr...@gmail.com` on 18 Mar 2012 at 11:43

**Comment by GoogleCodeExporter** [comment]
```
I've uploaded the package to pypi...I had to change the name to pyp.py, which I 
am not crazy about as it doubles the characters, but hopefully this should work 
for you guys.


```

Original comment by `tobyro...@gmail.com` on 19 Mar 2012 at 4:27

**Comment by GoogleCodeExporter** [comment]
```
after install pyp still dont work,

i see that it is in, 
-rw-r--r--  1 root  wheel  91030 Mar 19 10:54 
/Library/Python/2.7/site-packages/pyp.py
and it is not executable

for instance fabric puts file in
-rwxr-xr-x  1 root  admin  250 Feb 13 11:48 /usr/local/bin/fab


sudo pip install pyp   
Downloading/unpacking pyp
  Downloading pyp-2.11.tar.gz
  Running setup.py egg_info for package pyp

Installing collected packages: pyp
  Running setup.py install for pyp

Successfully installed pyp
Cleaning up...

zsh: command not found: pyp.py
zsh: command not found: pyp

PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bi
n:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```

Original comment by `ibrka...@gmail.com` on 19 Mar 2012 at 10:48

**Comment by GoogleCodeExporter** [comment]
```
Ok, thanks for the info. I'll see if I can get this in a more standard 
location. 
```

Original comment by `tobyro...@gmail.com` on 19 Mar 2012 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
It sounds to me like the setup.py is not quite right. You shouldn't have to 
rename pyp to pyp.py. I suspect you're doing that because otherwise 
distutils/setuptools isn't detecting pyp as a script or even as a Python file? 
If you have the write incantations it should work. For example, the following 
seems to work pretty well for me locally:

https://gist.github.com/2117804
```

Original comment by `msabr...@gmail.com` on 19 Mar 2012 at 4:20

**Comment by GoogleCodeExporter** [comment]
```
By the way, the key bit of magic here is the "scripts" keyword argument. More 
info on that at 
http://docs.python.org/distutils/setupscript.html#installing-scripts -- that 
whole page is a pretty quick and nicer primer on distutils.

If you've got the time, there was a nice talk at PyCon on posting to PyPI - 

https://us.pycon.org/2012/schedule/presentation/63/
http://pyvideo.org/video/678/sharing-is-caring-posting-to-the-python-package
```

Original comment by `msabr...@gmail.com` on 19 Mar 2012 at 4:47

**Comment by GoogleCodeExporter** [comment]
```
awesome, thanks for the help! I found the info for scripts this am, but I used 
(mostly) your setup file. It's on pypi now, hopefully in it's proper form. Let 
me know if it installs for you.

t


```

Original comment by `tobyro...@gmail.com` on 19 Mar 2012 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
now it works,
thx
```

Original comment by `ibrka...@gmail.com` on 19 Mar 2012 at 8:58

**Comment by GoogleCodeExporter** [comment]
```
ok, great, thanks for all your help everyone, especially msabramo!


```

Original comment by `tobyro...@gmail.com` on 19 Mar 2012 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
Update wiki with better notes about math usage
```

Original comment by `tobyro...@gmail.com` on 16 May 2012 at 9:36
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
it is no longer working

$ sudo pip install -U pyp
Downloading/unpacking pyp
  Downloading pyp-2.12.macosx-10.6-intel.tar.gz
  Running setup.py egg_info for package pyp
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/home/brko/mikro/build/pyp/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: 
'/home/brko/mikro/build/pyp/setup.py'
```

Original comment by `ibrka...@gmail.com` on 6 Sep 2012 at 10:38
